name: simpred
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pillow
  - msgpack-python
  - rdkit
  - cairo
  - pip
  - pip:
      - torch
      - torchvision
      - torch-geometric
      - pytest
